config/routes.rb
Rails.application.routes.draw do
  resources :bible
  resources :readers do
    post 'add_verse', on: :member
    post 'remove_verse', on: :member
  end
end

app/models/bible.rb
class Bible < ActiveRecord::Base
  include BibleData
end

app/models/concerns/bible_data.rb
module BibleData
  extend ActiveSupport::Concern

  included do
  end

  class_methods do
    def data
      [
        { 
          name: "Matthew",
          chapters: {
            1 => Array.new(25, false),
            2 => Array.new(23, false),
            3 => Array.new(17, false),
            4 => Array.new(25, false),
            5 => Array.new(48, false),
            6 => Array.new(34, false),
            7 => Array.new(29, false),
            8 => Array.new(34, false),
            9 => Array.new(38, false),
            10 => Array.new(42, false),
            11 => Array.new(30, false),
            12 => Array.new(50, false),
            13 => Array.new(58, false),
            14 => Array.new(36, false),
            15 => Array.new(39, false),
            16 => Array.new(28, false),
            17 => Array.new(27, false),
            18 => Array.new(35, false),
            19 => Array.new(30, false),
            20 => Array.new(34, false),
            21 => Array.new(46, false),
            22 => Array.new(46, false),
            23 => Array.new(39, false),
            24 => Array.new(51, false),
            25 => Array.new(46, false),
            26 => Array.new(75, false),
            27 => Array.new(66, false),
            28 => Array.new(20, false)
          } 
        },
        {
          name: "Mark",
          chapters: {
            1 => Array.new(45, false),
            2 => Array.new(28, false),
            3 => Array.new(35, false),
            4 => Array.new(41, false),
            5 => Array.new(43, false),
            6 => Array.new(56, false),
            7 => Array.new(37, false),
            8 => Array.new(38, false),
            9 => Array.new(50, false),
            10 => Array.new(52, false),
            11 => Array.new(33, false),
            12 => Array.new(44, false),
            13 => Array.new(37, false),
            14 => Array.new(72, false),
            15 => Array.new(47, false),
            16 => Array.new(20, false)
          }
        },
        {
          name: "Luke",
          chapters: {
            1 => Array.new(80, false),
            2 => Array.new(52, false),
            3 => Array.new(38, false),
            4 => Array.new(44, false),
            5 => Array.new(39, false),
            6 => Array.new(49, false),
            7 => Array.new(50, false),
            8 => Array.new(56, false),
            9 => Array.new(62, false),
            10 => Array.new(42, false),
            11 => Array.new(54, false),
            12 => Array.new(59, false),
            13 => Array.new(35, false),
            14 => Array.new(35, false),
            15 => Array.new(32, false),
            16 => Array.new(31, false),
            17 => Array.new(37, false),
            18 => Array.new(43, false),
            19 => Array.new(48, false),
            20 => Array.new(47, false),
            21 => Array.new(38, false),
            22 => Array.new(71, false),
            23 => Array.new(56, false),
            24 => Array.new(53, false)
          }
        },
        {
          name: "John",
          chapters: {
            1 => Array.new(51, false),
            2 => Array.new(25, false),
            3 => Array.new(36, false),
            4 => Array.new(54, false),
            5 => Array.new(47, false),
            6 => Array.new(71, false),
            7 => Array.new(53, false),
            8 => Array.new(59, false),
            9 => Array.new(41, false),
            10 => Array.new(42, false),
            11 => Array.new(57, false),
            12 => Array.new(50, false),
            13 => Array.new(38, false),
            14 => Array.new(31, false),
            15 => Array.new(27, false),
            16 => Array.new(33, false),
            17 => Array.new(26, false),
            18 => Array.new(40, false),
            19 => Array.new(42, false),
            20 => Array.new(31, false),
            21 => Array.new(25, false)
          }
        }
      ]
    end
  end
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  has_many :verses
  accepts_nested_attributes_for :verses, allow_destroy: true
end

app/models/verse.rb
class Verse < ActiveRecord::Base
  belongs_to :reader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bible_controller.rb
class BibleController < ApplicationController
 

  def index
    
  end

  def new
    @bible = Bible.create reading_record: Bible.data
    redirect_to @bible
  end

  def show
    @chapters_per_row = 10
    @bible = Bible.find(params[:id])
  end

  def update
    @bible = Bible.find(params[:id])
    @bible.update(bible_params)
  end

  def bible_params
    params[:bible].permit(:reading_record).tap do |white|
      white[:reading_record] = params[:bible][:reading_record]
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy, :add_verse, :remove_verse]

  # GET /readers
  # GET /readers.json
  def index
    @readers = Reader.all
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
    @chapters_per_row = 10
    @bible = Bible.data
    @verses = @reader.verses.index_by(&:number)
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to @reader, notice: 'Reader was successfully created.' }
        format.json { render :show, status: :created, location: @reader }
      else
        format.html { render :new }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readers/1
  # PATCH/PUT /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html { redirect_to @reader, notice: 'Reader was successfully updated.' }
        format.json { render :show, status: :ok, location: @reader }
      else
        format.html { render :edit }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_verse
    @reader.verses << Verse.create(verse_params)
    render json: @reader.verses, status: :ok
  end

  def remove_verse
    @reader.verses.where(number: verse_params[:number]).destroy_all
    render json: @reader.verses, status: :ok
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader.destroy
    respond_to do |format|
      format.html { redirect_to readers_url, notice: 'Reader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reader_params
      params[:reader].permit(:verses_attributes => [:number, :_destroy])
    end

    def verse_params
      params[:verse].permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bible_helper.rb
module BibleHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/bible/show.html.erb
<script>
  var BIBLE = <%= @bible.reading_record.to_json.html_safe %>;
  var ID    = <%= @bible.id %>
</script>

<label id="total-progress">Percent Read</label>
<div class="progress-bar-container">
  <div id="total-progress-bar"> </div>
</div>

<div class="container">

<% @bible.reading_record.each_with_index do |book, book_index| %>
  <div class="book-container">
    <h2 class="book"><%= book[:name] %></h2>

    <div class="chapters no-select">
      <% book[:chapters].keys.in_groups_of(@chapters_per_row, false) do |chapter_row| %>
      <div class="chapter-row">
      <% chapter_row.each do |number| 
        %><div class="chapter">
            <div class="chapter-number"><span class="progress"></span><%= number %></div>
            <div class="verses" data-verses="<%= book[:chapters][number].length %>">
              <% book[:chapters][number].each_with_index do |read, index| %><div id="<%= "#{book_index}-#{number}-#{index}" %>" class="verse-number <%= 'read' if read %>"><%= index+1 %></div><% end %>
            </div>
          </div><%
      end %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BibleTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/readers/_form.html.erb
<%= form_for(@reader) do |f| %>
  <% if @reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
      <% @reader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readers/edit.html.erb
<h1>Editing Reader</h1>

<%= render 'form' %>

<%= link_to 'Show', @reader %> |
<%= link_to 'Back', readers_path %>

app/views/readers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Readers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= link_to 'Show', reader %></td>
        <td><%= link_to 'Edit', edit_reader_path(reader) %></td>
        <td><%= link_to 'Destroy', reader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reader', new_reader_path %>

app/views/readers/new.html.erb
<h1>New Reader</h1>

<%= render 'form' %>

<%= link_to 'Back', readers_path %>

app/views/readers/show.html.erb
<script>
  var reader_id = <%= @reader.id %>
</script>

<label id="total-progress">Percent Read</label>
<div class="progress-bar-container">
  <div id="total-progress-bar"> </div>
</div>

<div class="container">

<% @bible.each_with_index do |book, book_index| %>
  <div class="book-container">
    <h2 class="book"><%= book[:name] %></h2>

    <div class="chapters no-select">
      <% book[:chapters].keys.in_groups_of(@chapters_per_row, false) do |chapter_row| %>
      <div class="chapter-row">
      <% chapter_row.each_with_index do |number, chapter_index| 
        %><div class="chapter">
            <div class="chapter-number"><span class="progress"></span><%= number %></div>
            <div class="verses" data-verses="<%= book[:chapters][number].length %>">
              <% book[:chapters][number].each_with_index do |read, verse_index| 
                verse_number = "#{book_index}-#{chapter_index}-#{verse_index}"
                %><div id="<%= verse_number %>" class="verse-number <%= 'read' if @verses[verse_number] %>"><%= verse_index+1 %></div><% end %>
            </div>
          </div><%
      end %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

</div>